theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Adaventure
    url: introduction
  - title: Example
    url: example
