theme: jekyll-theme-minimal
title: Adaventure - Hubs and Common knowledge
description: Here is a description
show_downloads: True
navigation:
  - title: Adaventure
    url: introduction
  - title: Example
    url: example
  
  input: GFM
